In [1]:
import pandas as pd

In [3]:
df = pd.read_csv("DelayedFlights.csv")

In [4]:
df.head(30)

,Unnamed: 0,Year,Month,DayofMonth,DayOfWeek,DepTime,CRSDepTime,ArrTime,CRSArrTime,UniqueCarrier,...,TaxiIn,TaxiOut,Cancelled,CancellationCode,Diverted,CarrierDelay,WeatherDelay,NASDelay,SecurityDelay,LateAircraftDelay
0,0,2008,1,3,4,2003.0,1955,2211.0,2225,WN,...,4.0,8.0,0,N,0,NaN,NaN,NaN,NaN,NaN
1,1,2008,1,3,4,754.0,735,1002.0,1000,WN,...,5.0,10.0,0,N,0,NaN,NaN,NaN,NaN,NaN
2,2,2008,1,3,4,628.0,620,804.0,750,WN,...,3.0,17.0,0,N,0,NaN,NaN,NaN,NaN,NaN
3,4,2008,1,3,4,1829.0,1755,1959.0,1925,WN,...,3.0,10.0,0,N,0,2.0,0.0,0.0,0.0,32.0
4,5,2008,1,3,4,1940.0,1915,2121.0,2110,WN,...,4.0,10.0,0,N,0,NaN,NaN,NaN,NaN,NaN
5,6,2008,1,3,4,1937.0,1830,2037.0,1940,WN,...,3.0,7.0,0,N,0,10.0,0.0,0.0,0.0,47.0
6,10,2008,1,3,4,706.0,700,916.0,915,WN,...,5.0,19.0,0,N,0,NaN,NaN,NaN,NaN,NaN
7,11,2008,1,3,4,1644.0,1510,1845.0,1725,WN,...,6.0,8.0,0,N,0,8.0,0.0,0.0,0.0,72.0
8,15,2008,1,3,4,1029.0,1020,1021.0,1010,WN,...,6.0,9.0,0,N,0,NaN,NaN,NaN,NaN,NaN
9,16,2008,1,3,4,1452.0,1425,1640.0,1625,WN,...,7.0,8.0,0,N,0,3.0,0.0,0.0,0.0,12.0
10,17,2008,1,3,4,754.0,745,940.0,955,WN,...,5.0,16.0,0,N,0,NaN,NaN,NaN,NaN,NaN
11,18,2008,1,3,4,1323.0,1255,1526.0,1510,WN,...,4.0,9.0,0,N,0,0.0,0.0,0.0,0.0,16.0
12,19,2008,1,3,4,1416.0,1325,1512.0,1435,WN,...,2.0,5.0,0,N,0,12.0,0.0,0.0,0.0,25.0
13,21,2008,1,3,4,1657.0,1625,1754.0,1735,WN,...,5.0,5.0,0,N,0,7.0,0.0,0.0,0.0,12.0
14,22,2008,1,3,4,1900.0,1840,1956.0,1950,WN,...,2.0,5.0,0,N,0,NaN,NaN,NaN,NaN,NaN
15,23,2008,1,3,4,1039.0,1030,1133.0,1140,WN,...,2.0,5.0,0,N,0,NaN,NaN,NaN,NaN,NaN
16,25,2008,1,3,4,1520.0,1455,1619.0,1605,WN,...,2.0,7.0,0,N,0,NaN,NaN,NaN,NaN,NaN
17,26,2008,1,3,4,1422.0,1255,1657.0,1610,WN,...,6.0,6.0,0,N,0,40.0,0.0,0.0,0.0,7.0
18,27,2008,1,3,4,1954.0,1925,2239.0,2235,WN,...,3.0,7.0,0,N,0,NaN,NaN,NaN,NaN,NaN
19,30,2008,1,3,4,2107.0,1945,2334.0,2230,WN,...,6.0,7.0,0,N,0,5.0,0.0,0.0,0.0,59.0
20,33,2008,1,3,4,1312.0,1300,1546.0,1550,WN,...,7.0,7.0,0,N,0,NaN,NaN,NaN,NaN,NaN
21,34,2008,1,3,4,1449.0,1430,1715.0,1720,WN,...,6.0,6.0,0,N,0,NaN,NaN,NaN,NaN,NaN
22,35,2008,1,3,4,1634.0,1555,1859.0,1845,WN,...,5.0,6.0,0,N,0,NaN,NaN,NaN,NaN,NaN
23,37,2008,1,3,4,1812.0,1650,1927.0,1815,WN,...,6.0,11.0,0,N,0,3.0,0.0,0.0,0.0,69.0
24,38,2008,1,3,4,1127.0,1105,1235.0,1230,WN,...,9.0,5.0,0,N,0,NaN,NaN,NaN,NaN,NaN
25,39,2008,1,3,4,1424.0,1355,1531.0,1520,WN,...,8.0,6.0,0,N,0,NaN,NaN,NaN,NaN,NaN
26,40,2008,1,3,4,1326.0,1230,1559.0,1530,WN,...,5.0,5.0,0,N,0,0.0,0.0,0.0,0.0,29.0
27,41,2008,1,3,4,1749.0,1725,2019.0,2030,WN,...,4.0,8.0,0,N,0,NaN,NaN,NaN,NaN,NaN
28,42,2008,1,3,4,726.0,720,958.0,1020,WN,...,4.0,8.0,0,N,0,NaN,NaN,NaN,NaN,NaN
29,43,2008,1,3,4,646.0,640,929.0,955,WN,...,3.0,9.0,0,N,0,NaN,NaN,NaN,NaN,NaN

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1936758 entries, 0 to 1936757
Data columns (total 30 columns):
 #   Column             Dtype
---  ------             -----
 0   Unnamed: 0         int64
 1   Year               int64
 2   Month              int64
 3   DayofMonth         int64
 4   DayOfWeek          int64
 5   DepTime            float64
 6   CRSDepTime         int64
 7   ArrTime            float64
 8   CRSArrTime         int64
 9   UniqueCarrier      object
 10  FlightNum          int64
 11  TailNum            object
 12  ActualElapsedTime  float64
 13  CRSElapsedTime     float64
 14  AirTime            float64
 15  ArrDelay           float64
 16  DepDelay           float64
 17  Origin             object
 18  Dest               object
 19  Distance           int64
 20  TaxiIn             float64
 21  TaxiOut            float64
 22  Cancelled          int64
 23  CancellationCode   object
 24  Diverted           int64
 25  CarrierDelay       float64
 26  WeatherDelay       float64
 27  NASDelay           float64
 28  SecurityDelay      float64
 29  LateAircraftDelay  float64
dtypes: float64(14), int64(11), object(5)
memory usage: 443.3+ MB

In [6]:
df.describe()

,Unnamed: 0,Year,Month,DayofMonth,DayOfWeek,DepTime,CRSDepTime,ArrTime,CRSArrTime,FlightNum,...,Distance,TaxiIn,TaxiOut,Cancelled,Diverted,CarrierDelay,WeatherDelay,NASDelay,SecurityDelay,LateAircraftDelay
count,1.936758e+06,1936758.0,1.936758e+06,1.936758e+06,1.936758e+06,1.936758e+06,1.936758e+06,1.929648e+06,1.936758e+06,1.936758e+06,...,1.936758e+06,1.929648e+06,1.936303e+06,1.936758e+06,1.936758e+06,1.247488e+06,1.247488e+06,1.247488e+06,1.247488e+06,1.247488e+06
mean,3.341651e+06,2008.0,6.111106e+00,1.575347e+01,3.984827e+00,1.518534e+03,1.467473e+03,1.610141e+03,1.634225e+03,2.184263e+03,...,7.656862e+02,6.812975e+00,1.823220e+01,3.268348e-04,4.003598e-03,1.917940e+01,3.703571e+00,1.502164e+01,9.013714e-02,2.529647e+01
std,2.066065e+06,0.0,3.482546e+00,8.776272e+00,1.995966e+00,4.504853e+02,4.247668e+02,5.481781e+02,4.646347e+02,1.944702e+03,...,5.744797e+02,5.273595e+00,1.433853e+01,1.807562e-02,6.314722e-02,4.354621e+01,2.149290e+01,3.383305e+01,2.022714e+00,4.205486e+01
min,0.000000e+00,2008.0,1.000000e+00,1.000000e+00,1.000000e+00,1.000000e+00,0.000000e+00,1.000000e+00,0.000000e+00,1.000000e+00,...,1.100000e+01,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00
25%,1.517452e+06,2008.0,3.000000e+00,8.000000e+00,2.000000e+00,1.203000e+03,1.135000e+03,1.316000e+03,1.325000e+03,6.100000e+02,...,3.380000e+02,4.000000e+00,1.000000e+01,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00
50%,3.242558e+06,2008.0,6.000000e+00,1.600000e+01,4.000000e+00,1.545000e+03,1.510000e+03,1.715000e+03,1.705000e+03,1.543000e+03,...,6.060000e+02,6.000000e+00,1.400000e+01,0.000000e+00,0.000000e+00,2.000000e+00,0.000000e+00,2.000000e+00,0.000000e+00,8.000000e+00
75%,4.972467e+06,2008.0,9.000000e+00,2.300000e+01,6.000000e+00,1.900000e+03,1.815000e+03,2.030000e+03,2.014000e+03,3.422000e+03,...,9.980000e+02,8.000000e+00,2.100000e+01,0.000000e+00,0.000000e+00,2.100000e+01,0.000000e+00,1.500000e+01,0.000000e+00,3.300000e+01
max,7.009727e+06,2008.0,1.200000e+01,3.100000e+01,7.000000e+00,2.400000e+03,2.359000e+03,2.400000e+03,2.400000e+03,9.742000e+03,...,4.962000e+03,2.400000e+02,4.220000e+02,1.000000e+00,1.000000e+00,2.436000e+03,1.352000e+03,1.357000e+03,3.920000e+02,1.316000e+03

In [8]:
df.isnull().sum()

Unnamed: 0                0
Year                      0
Month                     0
DayofMonth                0
DayOfWeek                 0
DepTime                   0
CRSDepTime                0
ArrTime                7110
CRSArrTime                0
UniqueCarrier             0
FlightNum                 0
TailNum                   5
ActualElapsedTime      8387
CRSElapsedTime          198
AirTime                8387
ArrDelay               8387
DepDelay                  0
Origin                    0
Dest                      0
Distance                  0
TaxiIn                 7110
TaxiOut                 455
Cancelled                 0
CancellationCode          0
Diverted                  0
CarrierDelay         689270
WeatherDelay         689270
NASDelay             689270
SecurityDelay        689270
LateAircraftDelay    689270
dtype: int64

In [10]:
df.describe(exclude='number')

       UniqueCarrier  TailNum   Origin     Dest CancellationCode
count        1936758  1936753  1936758  1936758          1936758
unique            20     5366      303      304                4
top               WN   N325SW      ATL      ORD                N
freq          377602      965   131613   108984          1936125

In [11]:
#sum of the uplicated values for the whole dataset
df.duplicated().sum()

0

In [12]:
#drop null values
df.dropna(axis=0,inplace=True)

In [13]:
# no null values
df.isna().sum()

Unnamed: 0           0
Year                 0
Month                0
DayofMonth           0
DayOfWeek            0
DepTime              0
CRSDepTime           0
ArrTime              0
CRSArrTime           0
UniqueCarrier        0
FlightNum            0
TailNum              0
ActualElapsedTime    0
CRSElapsedTime       0
AirTime              0
ArrDelay             0
DepDelay             0
Origin               0
Dest                 0
Distance             0
TaxiIn               0
TaxiOut              0
Cancelled            0
CancellationCode     0
Diverted             0
CarrierDelay         0
WeatherDelay         0
NASDelay             0
SecurityDelay        0
LateAircraftDelay    0
dtype: int64

In [14]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 1247486 entries, 3 to 1936755
Data columns (total 30 columns):
 #   Column             Non-Null Count    Dtype
---  ------             --------------    -----
 0   Unnamed: 0         1247486 non-null  int64
 1   Year               1247486 non-null  int64
 2   Month              1247486 non-null  int64
 3   DayofMonth         1247486 non-null  int64
 4   DayOfWeek          1247486 non-null  int64
 5   DepTime            1247486 non-null  float64
 6   CRSDepTime         1247486 non-null  int64
 7   ArrTime            1247486 non-null  float64
 8   CRSArrTime         1247486 non-null  int64
 9   UniqueCarrier      1247486 non-null  object
 10  FlightNum          1247486 non-null  int64
 11  TailNum            1247486 non-null  object
 12  ActualElapsedTime  1247486 non-null  float64
 13  CRSElapsedTime     1247486 non-null  float64
 14  AirTime            1247486 non-null  float64
 15  ArrDelay           1247486 non-null  float64
 16  DepDelay           1247486 non-null  float64
 17  Origin             1247486 non-null  object
 18  Dest               1247486 non-null  object
 19  Distance           1247486 non-null  int64
 20  TaxiIn             1247486 non-null  float64
 21  TaxiOut            1247486 non-null  float64
 22  Cancelled          1247486 non-null  int64
 23  CancellationCode   1247486 non-null  object
 24  Diverted           1247486 non-null  int64
 25  CarrierDelay       1247486 non-null  float64
 26  WeatherDelay       1247486 non-null  float64
 27  NASDelay           1247486 non-null  float64
 28  SecurityDelay      1247486 non-null  float64
 29  LateAircraftDelay  1247486 non-null  float64
dtypes: float64(14), int64(11), object(5)
memory usage: 295.0+ MB

In [15]:
#Unique values with its counts for each column 
for elem in df.columns[1:]:
    print(df[elem].value_counts())
    print("\n")

2008    1247486
Name: Year, dtype: int64


12    141373
6     136515
3     130999
2     128743
1     120786
7     119404
8     100602
4      97624
5      94771
11     63785
10     57079
9      55805
Name: Month, dtype: int64


22    48632
21    46162
7     44638
1     44304
27    43195
4     42653
15    42138
8     41784
20    41761
10    41700
19    41385
18    41025
14    41022
23    40875
26    40871
11    40547
6     40290
2     40165
24    39726
17    39518
9     39449
13    39102
12    38941
16    38255
5     38226
3     38111
28    37844
25    36828
30    36452
29    35015
31    26872
Name: DayofMonth, dtype: int64


5    214235
1    186860
4    186860
7    185184
2    169909
3    167704
6    136734
Name: DayOfWeek, dtype: int64


1800.0    2330
2000.0    2257
1900.0    2241
1700.0    2183
1730.0    2124
          ...
458.0        1
420.0        1
446.0        1
450.0        1
429.0        1
Name: DepTime, Length: 1435, dtype: int64


1800    9595
1700    9287
1900    8951
1855    8662
1850    8451
        ...
537        1
539        1
541        1
551        1
0          1
Name: CRSDepTime, Length: 1182, dtype: int64


2100.0    2132
2115.0    2037
2030.0    2036
2145.0    2017
2200.0    2016
          ...
508.0        8
456.0        8
451.0        6
437.0        5
454.0        2
Name: ArrTime, Length: 1440, dtype: int64


1930    5991
2015    5931
2000    5807
2005    5603
2045    5548
        ...
411        1
200        1
227        1
257        1
414        1
Name: CRSArrTime, Length: 1350, dtype: int64


WN    203559
AA    132257
MQ     97555
UA     95465
OO     88991
DL     72252
XE     72008
US     59508
CO     58958
EV     56781
NW     54744
YV     50646
FL     46991
OH     39292
B6     38232
9E     35630
AS     24012
F9     15940
HA      4325
AQ       340
Name: UniqueCarrier, dtype: int64


50      1053
321      930
75       922
16       915
40       902
        ...
7702       1
7701       1
7448       1
8403       1
7485       1
Name: FlightNum, Length: 7481, dtype: int64


N17175    686
N77278    679
N87353    678
N37208    665
N37342    660
         ...
N826MH      1
N859NW      1
N104UA      1
N702DN      1
N809NW      1
Name: TailNum, Length: 5349, dtype: int64


80.0     10854
75.0     10706
85.0     10524
90.0     10123
78.0     10093
         ...
670.0        1
619.0        1
672.0        1
702.0        1
656.0        1
Name: ActualElapsedTime, Length: 668, dtype: int64


75.0     31646
65.0     31382
70.0     30783
85.0     30664
80.0     29624
         ...
513.0        1
536.0        1
1.0          1
21.0         1
527.0        1
Name: CRSElapsedTime, Length: 497, dtype: int64


45.0      11778
52.0      11700
50.0      11687
46.0      11665
48.0      11660
          ...
627.0         1
632.0         1
616.0         1
1091.0        1
626.0         1
Name: AirTime, Length: 645, dtype: int64


15.0      32476
16.0      31198
17.0      30288
18.0      29816
19.0      28658
          ...
1123.0        1
1119.0        1
960.0         1
891.0         1
1072.0        1
Name: ArrDelay, Length: 1044, dtype: int64


25.0      23106
20.0      22956
30.0      21884
15.0      20195
22.0      19966
          ...
999.0         1
743.0         1
1521.0        1
1490.0        1
706.0         1
Name: DepDelay, Length: 1053, dtype: int64


ORD    90611
ATL    87741
DFW    62073
DEN    46477
EWR    36115
       ...
WYS        3
BLI        2
PUB        2
PIR        1
INL        1
Name: Origin, Length: 302, dtype: int64


ORD    79626
ATL    71607
DFW    45964
EWR    40873
DEN    38613
       ...
ITH       13
INL        9
BLI        7
BJI        4
PIR        1
Name: Dest, Length: 301, dtype: int64


337    8570
733    6518
761    5923
403    5890
296    5605
       ...
953       1
55        1
35        1
54        1
131       1
Name: Distance, Length: 1404, dtype: int64


5.0      195335
4.0      195098
6.0      152400
3.0      138217
7.0      116330
          ...
165.0         1
118.0         1
141.0         1
171.0         1
161.0         1
Name: TaxiIn, Length: 180, dtype: int64


11.0     72499
12.0     72076
10.0     71801
13.0     69669
14.0     65582
         ...
316.0        1
255.0        1
249.0        1
258.0        1
281.0        1
Name: TaxiOut, Length: 332, dtype: int64


0    1247486
Name: Cancelled, dtype: int64


N    1247486
Name: CancellationCode, dtype: int64


0    1247486
Name: Diverted, dtype: int64


0.0      591047
6.0       22799
7.0       21500
15.0      20361
8.0       19506
          ...
904.0         1
851.0         1
872.0         1
837.0         1
532.0         1
Name: CarrierDelay, Length: 983, dtype: int64


0.0      1148569
10.0        2868
6.0         2738
15.0        2709
7.0         2527
          ...
535.0          1
597.0          1
646.0          1
529.0          1
415.0          1
Name: WeatherDelay, Length: 599, dtype: int64


0.0      588995
1.0       34060
2.0       33177
3.0       31615
4.0       29825
          ...
418.0         1
505.0         1
518.0         1
473.0         1
706.0         1
Name: NASDelay, Length: 574, dtype: int64


0.0      1241481
7.0          350
6.0          327
8.0          286
9.0          278
          ...
108.0          1
175.0          1
178.0          1
112.0          1
136.0          1
Name: SecurityDelay, Length: 156, dtype: int64


0.0      555905
15.0      18632
16.0      17315
17.0      16393
18.0      15550
          ...
597.0         1
515.0         1
573.0         1
661.0         1
487.0         1
Name: LateAircraftDelay, Length: 564, dtype: int64

### Drop Unuseful columns

In [25]:
list = ['DayofMonth' , 'DayOfWeek' ,'Diverted' ,'CancellationCode' , 'Cancelled' ,'WeatherDelay', 'NASDelay' ,'SecurityDelay' ,'LateAircraftDelay']

In [26]:
# Drop BRAND_FULL_NAME column
for column in list:
    df.drop(columns= column,axis=1,inplace=True)

In [27]:
df.head(30)

,Unnamed: 0,Year,Month,DepTime,CRSDepTime,ArrTime,CRSArrTime,UniqueCarrier,FlightNum,TailNum,...,CRSElapsedTime,AirTime,ArrDelay,DepDelay,Origin,Dest,Distance,TaxiIn,TaxiOut,CarrierDelay
3,4,2008,1,1829.0,1755,1959.0,1925,WN,3920,N464WN,...,90.0,77.0,34.0,34.0,IND,BWI,515,3.0,10.0,2.0
5,6,2008,1,1937.0,1830,2037.0,1940,WN,509,N763SW,...,250.0,230.0,57.0,67.0,IND,LAS,1591,3.0,7.0,10.0
7,11,2008,1,1644.0,1510,1845.0,1725,WN,1333,N334SW,...,135.0,107.0,80.0,94.0,IND,MCO,828,6.0,8.0,8.0
9,16,2008,1,1452.0,1425,1640.0,1625,WN,675,N286WN,...,240.0,213.0,15.0,27.0,IND,PHX,1489,7.0,8.0,3.0
11,18,2008,1,1323.0,1255,1526.0,1510,WN,4,N674AA,...,135.0,110.0,16.0,28.0,IND,TPA,838,4.0,9.0,0.0
12,19,2008,1,1416.0,1325,1512.0,1435,WN,54,N643SW,...,70.0,49.0,37.0,51.0,ISP,BWI,220,2.0,5.0,12.0
13,21,2008,1,1657.0,1625,1754.0,1735,WN,623,N724SW,...,70.0,47.0,19.0,32.0,ISP,BWI,220,5.0,5.0,7.0
17,26,2008,1,1422.0,1255,1657.0,1610,WN,188,N215WN,...,195.0,143.0,47.0,87.0,ISP,FLL,1093,6.0,6.0,40.0
19,30,2008,1,2107.0,1945,2334.0,2230,WN,362,N798SW,...,165.0,134.0,64.0,82.0,ISP,MCO,972,6.0,7.0,5.0
23,37,2008,1,1812.0,1650,1927.0,1815,WN,422,N779SW,...,145.0,118.0,72.0,82.0,ISP,MDW,765,6.0,11.0,3.0
26,40,2008,1,1326.0,1230,1559.0,1530,WN,1056,N459WN,...,180.0,143.0,29.0,56.0,ISP,PBI,1052,5.0,5.0,0.0
32,48,2008,1,1450.0,1435,1806.0,1745,WN,3244,N475WN,...,130.0,121.0,21.0,15.0,JAN,BWI,888,7.0,8.0,0.0
33,49,2008,1,2245.0,1730,2354.0,1850,WN,186,N792SW,...,80.0,59.0,304.0,315.0,JAN,HOU,359,3.0,7.0,282.0
34,52,2008,1,2025.0,1940,2135.0,2100,WN,3154,N252WN,...,80.0,60.0,35.0,45.0,JAN,HOU,359,3.0,7.0,26.0
35,53,2008,1,1038.0,945,1314.0,1225,WN,1035,N346SW,...,100.0,81.0,49.0,53.0,JAN,MCO,587,8.0,7.0,7.0
36,54,2008,1,1900.0,1850,2123.0,2045,WN,205,N299WN,...,115.0,97.0,38.0,10.0,JAN,MDW,666,40.0,6.0,1.0
37,56,2008,1,948.0,925,959.0,940,WN,3430,N487WN,...,75.0,59.0,19.0,23.0,JAX,BHM,365,3.0,9.0,0.0
38,57,2008,1,646.0,620,725.0,655,WN,1580,N243WN,...,95.0,77.0,30.0,26.0,JAX,BNA,484,6.0,16.0,26.0
39,58,2008,1,1110.0,1040,1136.0,1110,WN,2195,N479WN,...,90.0,72.0,26.0,30.0,JAX,BNA,484,5.0,9.0,0.0
42,70,2008,1,1813.0,1735,1936.0,1905,WN,54,N643SW,...,150.0,125.0,31.0,38.0,JAX,HOU,816,6.0,12.0,11.0
44,74,2008,1,1734.0,1650,1941.0,1905,WN,23,N521SW,...,135.0,113.0,36.0,44.0,JAX,PHL,742,4.0,10.0,3.0
47,77,2008,1,958.0,900,1052.0,950,WN,1574,N791SW,...,50.0,36.0,62.0,58.0,JAX,TPA,180,4.0,14.0,0.0
49,79,2008,1,1538.0,1445,1753.0,1710,WN,500,N799SW,...,85.0,60.0,43.0,53.0,LAS,ABQ,487,4.0,11.0,15.0
50,81,2008,1,2248.0,2125,102.0,2345,WN,890,N618WN,...,80.0,60.0,77.0,83.0,LAS,ABQ,487,4.0,10.0,7.0
51,82,2008,1,1327.0,1230,1550.0,1500,WN,1171,N682SW,...,90.0,65.0,50.0,57.0,LAS,ABQ,487,3.0,15.0,50.0
53,86,2008,1,1832.0,1655,148.0,30,WN,302,N473WN,...,275.0,243.0,78.0,97.0,LAS,ALB,2237,3.0,10.0,8.0
54,87,2008,1,1229.0,1155,1633.0,1555,WN,1079,N351SW,...,120.0,91.0,38.0,34.0,LAS,AMA,758,5.0,28.0,3.0
56,89,2008,1,2118.0,2015,144.0,50,WN,2021,N499WN,...,155.0,127.0,54.0,63.0,LAS,AUS,1090,5.0,14.0,23.0
58,91,2008,1,1739.0,1640,114.0,25,WN,1018,N245WN,...,285.0,253.0,49.0,59.0,LAS,BDL,2298,9.0,13.0,19.0
59,94,2008,1,1325.0,1240,1841.0,1810,WN,419,N275WN,...,210.0,178.0,31.0,45.0,LAS,BNA,1588,6.0,12.0,2.0

In [28]:
df.isna().sum()

Unnamed: 0           0
Year                 0
Month                0
DepTime              0
CRSDepTime           0
ArrTime              0
CRSArrTime           0
UniqueCarrier        0
FlightNum            0
TailNum              0
ActualElapsedTime    0
CRSElapsedTime       0
AirTime              0
ArrDelay             0
DepDelay             0
Origin               0
Dest                 0
Distance             0
TaxiIn               0
TaxiOut              0
CarrierDelay         0
dtype: int64

In [29]:
#save the processed file 
df.to_csv('Airlines_delay_processed.csv')